blank_issues_enabled: false
contact_links:
  - name: Question
    url: https://github.com/2214962083/vue-superman/discussions/new?category=Q-A
    about: Ask a question or discuss about vue-superman
  - name: Ideas
    url: https://github.com/2214962083/vue-superman/discussions/new?category=Ideas
    about: Start a discussion to improve vue-superman
  - name: GitHub Sponsors
    url: https://github.com/sponsors/2214962083
    about: Like this project? Please consider supporting the author.
